# Generated by Django 6.0.6 on 2026-08-19 11:22

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0024_job_notifications"),
        ("extras", "0140_imageattachment_image_size"),
        ("users", "0016_default_ordering_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                ("name", models.CharField(max_length=200)),
                ("source_xml", models.TextField(blank=True, default="")),
                ("svg_cache", models.TextField(blank=True, default="", editable=False)),
                ("content_hash", models.CharField(blank=True, default="", editable=False, max_length=64)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.owner"
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Diagram",
                "verbose_name_plural": "Diagrams",
                "ordering": ("name", "pk"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DiagramAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="netbox_drawio.diagram",
                    ),
                ),
                ("object_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.objecttype")),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Diagram Assignment",
                "verbose_name_plural": "Diagram Assignments",
                "ordering": ("diagram", "object_type", "object_id"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="diagram",
            index=models.Index(fields=["name", "id"], name="netbox_drawio_diagram_name_idx"),
        ),
        migrations.AddIndex(
            model_name="diagramassignment",
            index=models.Index(fields=["object_type", "object_id"], name="netbox_drawio_assign_ot_id_idx"),
        ),
        migrations.AddConstraint(
            model_name="diagramassignment",
            constraint=models.UniqueConstraint(
                fields=("diagram", "object_type", "object_id"), name="netbox_drawio_unique_assignment"
            ),
        ),
    ]
